import turtle
def move1(t,n,k,l):
    t.left((90*k)/n)
    t.forward(l)
def move2(t,i,j):
    t.left(i)
    t.forward(j)
def main():
    wd = turtle.Screen()
    s = turtle.Turtle()
    s.shape("circle")
    s.color("yellow")
    m = turtle.Turtle()
    m.shape("circle")
    m.color("blue")
    m.speed(0)
    v = turtle.Turtle()
    v.shape("circle")
    v.color("green")
    v.speed(0)
    e = turtle.Turtle()
    e.shape("circle")
    e.color("red")
    e.speed(0)
    ma = turtle.Turtle()
    ma.shape("circle")
    ma.color("black")
    ma.speed(0)
    j = turtle.Turtle()
    j.shape("circle")
    j.color("orange")
    j.speed(0)
    s = turtle.Turtle()
    s.shape("circle")
    s.color("hotpink")
    s.speed(0)          #define the sun and its six planets
    m.up()
    m.goto(20,0)
    m.down()
    v.up()
    v.goto(40,0)
    v.down()
    e.up()
    e.goto(60,0)
    e.down()
    ma.up()
    ma.goto(80,0)
    ma.down()
    j.up()
    j.goto(100,0)
    j.down()
    s.up()
    s.goto(120,0)
    s.down()
    m.left(90)
    v.left(90)
    e.left(90)
    ma.left(90)
    j.left(90)
    s.left(90)#initialize the position of the planets
    n = 150
    #for i in range(n): #let the planets start their show!
        #move1(m,n,12,5)
        #move1(v,n,8,6)
        #move1(e,n,7,7)
        #move1(ma,n,6,8)
        #move1(j,n,5,9)
        #move1(s,n,4,10)
    for i in [1,2,3,4,5,6,7,8,9,10,11,12,12,12,12,11,10,9,8,7,6,5,4,3,2,1]:
        k = 13-i
        move2(m,i,k)
        move2(v,i,2*k)
        move2(e,i,3*k)
        move2(ma,i,4*k)
        move2(j,i,5*k)
        move2(s,i,6*k)
    for i in [1,2,3,4,5,6,7,8,9,10,11,12,12,12,12,11,10,9,8,7,6,5,4,3,2,1]:
        k = 13-i
        move2(m,i,k)
        move2(v,i,2*k)
        move2(e,i,3*k)
        move2(ma,i,4*k)
        move2(j,i,5*k)
        move2(s,i,6*k)
    wd.exitonclick()
if __name__ =="__main__":
    main()
